[package]
name = "raspi3_glue"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]

[dependencies]
# cortex-a = "1.0.0"
cortex-a = { path = "../../../cortex-a" }
panic-abort = "0.2.0"
r0 = "0.2.2"
