[package]
name = "kernel8"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]
build = "build.rs"

[dependencies]
raspi3_glue = { path = "raspi3_glue" }
# cortex-a = "1.0.0"
cortex-a = { path = "../../cortex-a" }
register = "0.1.1"
rlibc = "1.0.0"
