[package]
name = "kernel8"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]
build = "build.rs"

[dependencies]
raspi3_glue = { path = "raspi3_glue" }
volatile-register = "0.2.0"
